### ISSUE TITLE
出大事了，更新完成之后现在一压制就报错

### ISSUE THREAD

**Issue by OKtheMirror** [YohoYang/VSGUI#8]
一开始压制就说遇到了致命错误，这怎么办啊

**Comment by YohoYang** [comment]
**1. 有报错麻烦找到文件夹内的log目录，找到crash日志，并贴上来，不然无法排查问题。**
2. 更新至1.0.0版本后，原先版本添加的任务不可再使用，需要重新添加。
3. 在线更新可能根据网络出现问题，在设置界面点击【联网校验软件完整性】或者重新在release中下载一个新的压缩包来测试

**Comment by OKtheMirror** [comment]
> **1. 有报错麻烦找到文件夹内的log目录，找到crash日志，并贴上来，不然无法排查问题。** 2. 更新至1.0.0版本后，原先版本添加的任务不可再使用，需要重新添加。 3. 在线更新可能根据网络出现问题，在设置界面点击【联网校验软件完整性】或者重新在release中下载一个新的压缩包来测试

我试了四次全部报错，都要贴过来吗

**Comment by OKtheMirror** [comment]
> **1. 有报错麻烦找到文件夹内的log目录，找到crash日志，并贴上来，不然无法排查问题。** 2. 更新至1.0.0版本后，原先版本添加的任务不可再使用，需要重新添加。 3. 在线更新可能根据网络出现问题，在设置界面点击【联网校验软件完整性】或者重新在release中下载一个新的压缩包来测试

System.NullReferenceException: Object reference not set to an instance of an object.
   at VSGUI.API.EncoderApi.GetEncoderPath(String type, Int32 encoderid)
   at VSGUI.API.QueueApi.UpdateProgressStatus(String queueid, String message)
   at VSGUI.MainWindow.<>c__DisplayClass32_0.<StartQueueJob>g__DataReceived|2(String data, Boolean processIsExited)
   at VSGUI.API.ProcessApi.RunProcess(String clipath, String common, Action`2 inDataReceived, Action inExited, Action`1 processid, Encoding outputEncoding, Boolean isQueueJob)
   at VSGUI.API.ProcessApi.RunProcess(String clipath, String common, Action`2 inDataReceived, Action inExited, Action`1 processid, Encoding outputEncoding, Boolean isQueueJob)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
这是其中一次的

**Comment by YohoYang** [comment]
> > **1. 有报错麻烦找到文件夹内的log目录，找到crash日志，并贴上来，不然无法排查问题。** 2. 更新至1.0.0版本后，原先版本添加的任务不可再使用，需要重新添加。 3. 在线更新可能根据网络出现问题，在设置界面点击【联网校验软件完整性】或者重新在release中下载一个新的压缩包来测试
> 
> System.NullReferenceException: Object reference not set to an instance of an object. at VSGUI.API.EncoderApi.GetEncoderPath(String type, Int32 encoderid) at VSGUI.API.QueueApi.UpdateProgressStatus(String queueid, String message) at VSGUI.MainWindow.<>c__DisplayClass32_0.g__DataReceived|2(String data, Boolean processIsExited) at VSGUI.API.ProcessApi.RunProcess(String clipath, String common, Action`2 inDataReceived, Action inExited, Action`1 processid, Encoding outputEncoding, Boolean isQueueJob) at VSGUI.API.ProcessApi.RunProcess(String clipath, String common, Action`2 inDataReceived, Action inExited, Action`1 processid, Encoding outputEncoding, Boolean isQueueJob) at System.Threading.Tasks.Task.<>c.b__128_1(Object state) at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi) at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state) at System.Threading.QueueUserWorkItemCallback.Execute() at System.Threading.ThreadPoolWorkQueue.Dispatch() at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart() at System.Threading.Thread.StartCallback() 这是其中一次的

看起来是新增加的自定义编码器加上的路径导致的影响，您应该使用的是自己的编码器配置，麻烦打开后重新保存一下应该就好了

**Comment by YohoYang** [comment]
> > **1. 有报错麻烦找到文件夹内的log目录，找到crash日志，并贴上来，不然无法排查问题。** 2. 更新至1.0.0版本后，原先版本添加的任务不可再使用，需要重新添加。 3. 在线更新可能根据网络出现问题，在设置界面点击【联网校验软件完整性】或者重新在release中下载一个新的压缩包来测试
> 
> System.NullReferenceException: Object reference not set to an instance of an object. at VSGUI.API.EncoderApi.GetEncoderPath(String type, Int32 encoderid) at VSGUI.API.QueueApi.UpdateProgressStatus(String queueid, String message) at VSGUI.MainWindow.<>c__DisplayClass32_0.g__DataReceived|2(String data, Boolean processIsExited) at VSGUI.API.ProcessApi.RunProcess(String clipath, String common, Action`2 inDataReceived, Action inExited, Action`1 processid, Encoding outputEncoding, Boolean isQueueJob) at VSGUI.API.ProcessApi.RunProcess(String clipath, String common, Action`2 inDataReceived, Action inExited, Action`1 processid, Encoding outputEncoding, Boolean isQueueJob) at System.Threading.Tasks.Task.<>c.b__128_1(Object state) at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi) at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state) at System.Threading.QueueUserWorkItemCallback.Execute() at System.Threading.ThreadPoolWorkQueue.Dispatch() at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart() at System.Threading.Thread.StartCallback() 这是其中一次的

我增加一下兼容性，在晚上更新1.0.5

**Comment by YohoYang** [comment]
> > **1. 有报错麻烦找到文件夹内的log目录，找到crash日志，并贴上来，不然无法排查问题。** 2. 更新至1.0.0版本后，原先版本添加的任务不可再使用，需要重新添加。 3. 在线更新可能根据网络出现问题，在设置界面点击【联网校验软件完整性】或者重新在release中下载一个新的压缩包来测试
> 
> 我试了四次全部报错，都要贴过来吗

已更新，更新至1.0.5应该可以解决问题，感谢反馈~ 下次直接带上报错可以修的更快~

**Comment by OKtheMirror** [comment]
> > > **1. 有报错麻烦找到文件夹内的log目录，找到crash日志，并贴上来，不然无法排查问题。** 2. 更新至1.0.0版本后，原先版本添加的任务不可再使用，需要重新添加。 3. 在线更新可能根据网络出现问题，在设置界面点击【联网校验软件完整性】或者重新在release中下载一个新的压缩包来测试
> > 
> > 
> > 我试了四次全部报错，都要贴过来吗
> 
> 已更新，更新至1.0.5应该可以解决问题，感谢反馈~ 下次直接带上报错可以修的更快~

问题解决了，谢谢
